name: A-TO-B:CUSTOM_BRANCH
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@v2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: jenkey2011/vuepress-deploy-demo-target
          TARGET_BRANCH: custom_branch
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: blog/.vuepress/dist/
          COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy