name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.WOW4J }}
          TARGET_REPO: timchen525/wow4j
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist